spring:
   profiles:
     active: dev

server.tomcat.accesslog:
    # Enable access log:
    enabled: true

    # Directory in which log files are created. Can be relative to the tomcat base dir or absolute:
    directory: /var/log/tomcat7/

    # Format pattern for access logs:
    pattern: '%h %l %u %t "%r" %s %b %D'

    # Log file name suffix:
    suffix: .log

elastic:
  cluster:
    name: byr-application
    index: index
    type: post
  size: 10

---

spring:
  profiles: production
elastic:
  server:
    address: localhost
    port: 9300

---

spring:
  profiles: dev
elastic:
  server:
    address: 182.254.242.25
    port: 9300